//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.message {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PMS.message.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 用户无权限或密码错误 的本地化字符串。
        /// </summary>
        internal static string m001 {
            get {
                return ResourceManager.GetString("m001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此用户不存在 的本地化字符串。
        /// </summary>
        internal static string m002 {
            get {
                return ResourceManager.GetString("m002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码2不能为空 的本地化字符串。
        /// </summary>
        internal static string m003 {
            get {
                return ResourceManager.GetString("m003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码1不能为空 的本地化字符串。
        /// </summary>
        internal static string m004 {
            get {
                return ResourceManager.GetString("m004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户编号不能为空 的本地化字符串。
        /// </summary>
        internal static string m005 {
            get {
                return ResourceManager.GetString("m005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名不能为空 的本地化字符串。
        /// </summary>
        internal static string m006 {
            get {
                return ResourceManager.GetString("m006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入两次密码不一致 的本地化字符串。
        /// </summary>
        internal static string m007 {
            get {
                return ResourceManager.GetString("m007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此用户当前已作废，不能再次作废 的本地化字符串。
        /// </summary>
        internal static string m008 {
            get {
                return ResourceManager.GetString("m008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此用户当前有效，不能恢复 的本地化字符串。
        /// </summary>
        internal static string m009 {
            get {
                return ResourceManager.GetString("m009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有权限更改其它用户的密码 的本地化字符串。
        /// </summary>
        internal static string m010 {
            get {
                return ResourceManager.GetString("m010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前列表无数据，不允许导出 的本地化字符串。
        /// </summary>
        internal static string m011 {
            get {
                return ResourceManager.GetString("m011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此用户无效，不允许登陆 的本地化字符串。
        /// </summary>
        internal static string m012 {
            get {
                return ResourceManager.GetString("m012", resourceCulture);
            }
        }
    }
}
